version: '2.0'
services:
    node1:
      container_name: ${PROJECT_NAME}
      image: krkrishna011/apachejmeter-master:v0.2
      volumes:
        - /opt/aptsac/jmeter/workspace/${PROJECT_NAME}:/opt/jmeter/bin/sharedfolder/Script
        - /opt/aptsac/jmeter/workspace/report:/opt/jmeter/bin/sharedfolder/Report
        - /opt/aptsac/jmeter/workspace/results:/opt/jmeter/bin/Results
      environment:
        - Extra_params=${Extra_params}
        - Users=${Users}
        - Duration=${Duration}
        - BUILD_NUMBER=${BUILD_NUMBER}
        - PROJECT_NAME=${PROJECT_NAME}
        
      command: sh +x /opt/jmeter/bin/sharedfolder/Script/script_jmeter.sh
      
    lighthouse:
      container_name: lighthouse
      image: mahireddy23/lighthouse:v0.1
      volumes:
        - /opt/aptsac/lighthouse/report:/report
      command: lighthouse --chrome-flags="--headless --disable-gpu --no-sandbox" --throttling.cpuSlowdownMultiplier=2 https://www.demoblaze.com --output=html
    
    filebeatapts:
      container_name: filebeat-container1
      user: root
      build:
        context: filebeat/
        args:
          ELK_VERSION: 7.9.2
      volumes:
        - /opt/aptsac/jmeter/workspace/report/:/var/log/jmeter/
      command: ["--strict.perms=false"]
      depends_on:
        - node1
        
