version: '2.0'
services: 
    Lighthouse:
      container_name: lighthouse
      image: lighthouse:v9.5.0
      build:
        context: lighthouse/
      volumes:
        - /opt/aptsac/jmeter/workspace/${PROJECT_NAME}:/report
        - /opt/aptsac/jmeter/workspace/report:/usr/tmp/

      environment:
        - BUILD_NUMBER=${BUILD_NUMBER}
        - PROJECT_NAME=${PROJECT_NAME}
        - Config=${Config}
      stdin_open: true
      tty: true

      command: sh +x /report/lighthouse.sh
